In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
cat = pd.read_csv("data/cats_dataset.csv")
cat

Breed  Age (Years)  Weight (kg)          Color  Gender
0          Russian Blue           19            7  Tortoiseshell  Female
1      Norwegian Forest           19            9  Tortoiseshell  Female
2             Chartreux            3            3          Brown  Female
3               Persian           13            6          Sable  Female
4               Ragdoll           10            8          Tabby    Male
..                  ...          ...          ...            ...     ...
995   British Shorthair           19            5           Gray  Female
996   British Shorthair           11            2        Bicolor  Female
997            Savannah           12            5        Bicolor  Female
998  American Shorthair            8            3  Tortoiseshell  Female
999           Chartreux           11            4          Sable  Female

[1000 rows x 5 columns]

In [3]:
cat["Gender"] = cat["Gender"].replace({"Male": 1, "Female": 0})
cat["Gender"]

C:\Users\THINH\AppData\Local\Temp\ipykernel_10720\3747136074.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cat["Gender"] = cat["Gender"].replace({"Male": 1, "Female": 0})


0      0
1      0
2      0
3      0
4      1
      ..
995    0
996    0
997    0
998    0
999    0
Name: Gender, Length: 1000, dtype: int64

In [4]:
cat["Gender"] = cat["Gender"].astype(int)

In [5]:
cat["Gender"].dtype

dtype('int64')

In [6]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
cat["Breed_encoded"] = le.fit_transform(cat["Breed"])
cat["Color_encoded"] = le.fit_transform(cat["Color"])
print(cat[["Breed", "Breed_encoded"]].head())

              Breed  Breed_encoded
0      Russian Blue             21
1  Norwegian Forest             16
2         Chartreux              7
3           Persian             19
4           Ragdoll             20


In [7]:
cat = cat.drop("Breed", axis = 1)

In [8]:
cat = cat.drop("Color", axis = 1)

In [9]:
cat

Age (Years)  Weight (kg)  Gender  Breed_encoded  Color_encoded
0             19            7       0             21             12
1             19            9       0             16             12
2              3            3       0              7              3
3             13            6       0             19             10
4             10            8       1             20             11
..           ...          ...     ...            ...            ...
995           19            5       0              5              6
996           11            2       0              5              0
997           12            5       0             22              0
998            8            3       0              1             12
999           11            4       0              7             10

[1000 rows x 5 columns]

In [10]:
x = cat.drop("Gender", axis = 1)

y = cat["Gender"]

In [11]:
x

Age (Years)  Weight (kg)  Breed_encoded  Color_encoded
0             19            7             21             12
1             19            9             16             12
2              3            3              7              3
3             13            6             19             10
4             10            8             20             11
..           ...          ...            ...            ...
995           19            5              5              6
996           11            2              5              0
997           12            5             22              0
998            8            3              1             12
999           11            4              7             10

[1000 rows x 4 columns]

In [12]:
y

0      0
1      0
2      0
3      0
4      1
      ..
995    0
996    0
997    0
998    0
999    0
Name: Gender, Length: 1000, dtype: int64

In [13]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [14]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.6)
clf.fit(x_train,y_train)

RandomForestClassifier()

In [15]:
x_train

Age (Years)  Weight (kg)  Breed_encoded  Color_encoded
405            2            9             10              6
275            8            4             22              1
771           15            8              2              9
42             7            9             12             11
468           16            8             10              6
..           ...          ...            ...            ...
941           12            5              6             13
810            4            8             26              7
465            4            2              1              1
137            1            5              9              2
503            9            2              6              6

[400 rows x 4 columns]

In [16]:
# dự đoán
y_preds = clf.predict(x_test)
y_preds

array([1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,

In [17]:
# Đánh giá dữ liệu được dự đoán
clf.score(x_train, y_train)

1.0

In [18]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds), confusion_matrix(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.50      0.50      0.50       299
           1       0.51      0.51      0.51       301

    accuracy                           0.51       600
   macro avg       0.50      0.50      0.50       600
weighted avg       0.50      0.51      0.50       600
 [[149 150]
 [147 154]]


In [19]:
# Cải thiện mô hình
np.random.seed(42)
for i in range(10,100,10):
    print(f"Mẫu {i} ...");
    clf = RandomForestClassifier(n_estimators= i).fit(x_train,y_train)
    print(f"Độ chính xác của test set = {clf.score(x_test,y_test)*100:.2f}% ")

Mẫu 10 ...
Độ chính xác của test set = 51.83% 
Mẫu 20 ...
Độ chính xác của test set = 49.67% 
Mẫu 30 ...
Độ chính xác của test set = 52.67% 
Mẫu 40 ...
Độ chính xác của test set = 51.67% 
Mẫu 50 ...
Độ chính xác của test set = 48.33% 
Mẫu 60 ...
Độ chính xác của test set = 50.50% 
Mẫu 70 ...
Độ chính xác của test set = 50.33% 
Mẫu 80 ...
Độ chính xác của test set = 51.67% 
Mẫu 90 ...
Độ chính xác của test set = 51.00% 


In [20]:
# Thấp quoãi ò

In [21]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import GradientBoostingRegressor

# Giả sử X, y đã có sẵn
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

# Khởi tạo mô hình Gradient Boosting
gb_model = GradientBoostingRegressor(
    n_estimators=200,   # số lượng cây
    learning_rate=0.1,  # tốc độ học
    max_depth=4,        # độ sâu của cây
    random_state=42
)

# Huấn luyện
gb_model.fit(X_train, y_train)

# Dự đoán
y_pred = gb_model.predict(X_test)

# Đánh giá
print("MSE:", mean_squared_error(y_test, y_pred))
print("R²:", r2_score(y_test, y_pred))
# Kết quả cùi bắp

MSE: 0.3212026727887045
R²: -0.2853248210832513


In [22]:
cat = pd.read_csv("data/cats_dataset.csv")
cat.head()

Breed  Age (Years)  Weight (kg)          Color  Gender
0      Russian Blue           19            7  Tortoiseshell  Female
1  Norwegian Forest           19            9  Tortoiseshell  Female
2         Chartreux            3            3          Brown  Female
3           Persian           13            6          Sable  Female
4           Ragdoll           10            8          Tabby    Male

In [23]:
cat.isna().sum()

Breed          0
Age (Years)    0
Weight (kg)    0
Color          0
Gender         0
dtype: int64

In [24]:
cat["Gender"] = cat["Gender"].replace({"Male": 0, "Female": 1})

C:\Users\THINH\AppData\Local\Temp\ipykernel_10720\3280770699.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cat["Gender"] = cat["Gender"].replace({"Male": 0, "Female": 1})


In [25]:
cat

Breed  Age (Years)  Weight (kg)          Color  Gender
0          Russian Blue           19            7  Tortoiseshell       1
1      Norwegian Forest           19            9  Tortoiseshell       1
2             Chartreux            3            3          Brown       1
3               Persian           13            6          Sable       1
4               Ragdoll           10            8          Tabby       0
..                  ...          ...          ...            ...     ...
995   British Shorthair           19            5           Gray       1
996   British Shorthair           11            2        Bicolor       1
997            Savannah           12            5        Bicolor       1
998  American Shorthair            8            3  Tortoiseshell       1
999           Chartreux           11            4          Sable       1

[1000 rows x 5 columns]

In [26]:
x = cat.drop("Gender", axis = 1)
y = cat["Gender"]
x.head(),y.head()

(              Breed  Age (Years)  Weight (kg)          Color
 0      Russian Blue           19            7  Tortoiseshell
 1  Norwegian Forest           19            9  Tortoiseshell
 2         Chartreux            3            3          Brown
 3           Persian           13            6          Sable
 4           Ragdoll           10            8          Tabby,
 0    1
 1    1
 2    1
 3    1
 4    0
 Name: Gender, dtype: int64)

In [27]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

cate = ["Breed","Color","Age (Years)", "Weight (kg)"]
one_hot = OneHotEncoder(sparse_output=False)
trans = ColumnTransformer([("one_hot",
                         one_hot,
                         cate)],
                         remainder = "passthrough")
xx = trans.fit_transform(x)
xx

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(1000, 72))

In [28]:
pd.DataFrame(xx)

0    1    2    3    4    5    6    7    8    9   ...   62   63   64  \
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
995  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0   
996  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0   
997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0   

      65   66   67   68   69   70   71  
0    0.0  0.0  0.0  0.0  1.0  0.0  0.0  
1    0.0  0.0  0.0  0.0  0.0  0.0  1.0  
2    1.0  0.0  0.0  0.0  0.0  0.0  0.0  
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  
4    0.0  0.0  0.0  0.0  0.0  1.0  0.0  
..   ...  ...  ...  ...  ...  ...  ...  
995  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
997  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
998  1.0  0.0  0.0  0.0  0.0  0.0  0.0  
999  0.0  1.0  0.0  0.0  0.0  0.0  0.0  

[1000 rows x 72 columns]

In [29]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(random_state=42)

np.random.seed(42)
x_train,x_test,y_train,y_test = train_test_split(xx,
                                                y, test_size = 0.2)
model.fit(x_train,y_train)
model.score(x_test,y_test)

-0.17899598672802464

In [32]:
xx

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(1000, 72))

In [33]:
X_train, X_test, y_train, y_test = train_test_split(
    xx, y, test_size=0.2, random_state=42
)

# Khởi tạo mô hình Gradient Boosting
gb_model = GradientBoostingRegressor(
    n_estimators=200,   # số lượng cây
    learning_rate=0.1,  # tốc độ học
    max_depth=4,        # độ sâu của cây
    random_state=42
)

# Huấn luyện
gb_model.fit(X_train, y_train)

# Dự đoán
y_pred = gb_model.predict(X_test)

# Đánh giá
print("MSE:", mean_squared_error(y_test, y_pred))
print("R²:", r2_score(y_test, y_pred))

MSE: 0.3285709416772605
R²: -0.31480969058527597


In [34]:
x_train, x_test, y_train, y_test = train_test_split(xx,y, test_size = 0.6)
clf.fit(x_train,y_train)

RandomForestClassifier(n_estimators=90)